services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      
      # 配置文件
      - /root/Docker/nginx/conf.d/:/etc/nginx/conf.d/
      # SSL证书
      - /root/Docker/nginx/ssl/:/etc/nginx/ssl/

      - /root/Docker/nginx/web/:/usr/share/nginx/web/
